defaults: &defaults

  # sites hosts
  # session expire seconds
  # admin role account
  URL_HOST: 192.168.1.100:3000
  URL_SCHEMA: http
  SESSION_EXPIRE: '60'
  ADMIN: 'admin@demo.exchange'
  TIMEZONE: 'Central Time (US & Canada)'

  REDIS_URL: redis://127.0.0.1:6379

  # below settings only in production env
  # system notify mail settings
  # --------------------------------------------------------------
  SMTP_PORT: YOUR_SMTP_PORT
  SMTP_DOMAIN: YOUR_SMTP_DOMAIN
  SMTP_ADDRESS: YOUR_SMTP_ADDRESS
  SMTP_USERNAME: YOUR_SMTP_USERNAME
  SMTP_PASSWORD: YOUR_SMTP_PASSWORD
  SMTP_AUTHENTICATION: plain # could be plain, login or cram_md5

  SUPPORT_MAIL: support@demo.exchange
  SYSTEM_MAIL_FROM: system@demo.exchange
  SYSTEM_MAIL_TO: group@demo.exchange
  OPERATE_MAIL_TO: support@demo.exchange

  # WebSocket Streaming API settings
  # --------------------------------------------------------------
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: '8080'
  # Uncomment below to enable secure WebSocket (wss)
  #WEBSOCKET_SSL_KEY: 'your_server.key'
  #WEBSOCKET_SSL_CERT: 'your_server.crt'

  # pusher settings
  # --------------------------------------------------------------
  # dependence Pusher (http://pusher.com) service
  # you can change your key for production environment.
  # we support development key and secret
  # uncomment below line only development or test
  #
  # PUSHER_APP: 65910
  # PUSHER_KEY: 50d404c35db92d736a57
  # PUSHER_SECRET: 75d6e6685209cc60cc4d

  PUSHER_APP: 533502
  PUSHER_KEY: a383fe860e7492137487
  PUSHER_SECRET: ed3c5a6440a99f947b1e
  PUSHER_HOST: api.pusher.com
  # Careful in Host - pusher zone binding
  PUSHER_PORT: '80'
  PUSHER_WS_PORT: '80'
  PUSHER_WSS_PORT: '443'
  PUSHER_ENCRYPTED: true

  # twilio setting
  # --------------------------------------------------------------
  # https://github.com/twilio/twilio-ruby
  #
  TWILIO_NUMBER: YOUR_TWILIO_NUMBER
  TWILIO_SID: YOUR_TWILIO_SID
  TWILIO_TOKEN: YOUR_TWILIO_TOKEN


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
